### PR TITLE
Issue 14

### PR DESCRIPTION
**Pull request by MatthewBerglund**
Hey @motine here's the new layout for fetched articles. Let me know what you think!

### CODE REVIEW

**Comment by motine** [comment]
let’s pretend i am a not-so-technical PO. can you provide a testing system for me?

**Comment by MatthewBerglund** [comment]
@motine You can preview the app with the new design here: https://matthewberglund.github.io/nytimes-article-searcher/

The design attempts to account for missing images, abstracts and tags. To preview articles where these elements are missing, perform a search for something like "Dogs" without setting a date range, then sort the results by "Oldest".

**Comment by motine** [comment]
great stuff. thanks for putting this out there.

The design looks great.

On thing that I realized is, that it is not really clear which elements are clickable. "search" is yellow, the filter is blue, others are black... can we find a color code for this?

here: maybe consider if my suggestions are still related to this pull request.
for later in the job: lowering the feedback barriers is a good thing

**Comment by MatthewBerglund** [comment]
Great, thanks for the feedback. I'll open a separate issue for color-coding interactive elements, and I'll get back to you with a proposal.

**Pull request merged**
